In [ ]:
import numpy as np

In [ ]:
escalar = 5.679
vector = np.array([1,2,3])
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
tensor = np.array([
    [[255,0,0],[0,255,0]],
    [[11,12,13],[14,15, 15]]
])

<ipython-input-22-ff63f297d28d>:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  tensor = np.array([


Evaluar las dimensiones de los diferentes objetos matemáticos.

In [ ]:
escalar.shape

AttributeError: 'float' object has no attribute 'shape'

In [ ]:
vector.shape

(3,)

In [ ]:
len(vector)

3

In [ ]:
matriz.shape

(3, 3)

In [ ]:
print(matriz) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
matriz.size #cantidad total de elementos de la matriz

9

In [ ]:
print(tensor)

[[[255   0   0]
  [  0 255   0]]

 [[ 11  12  13]
  [ 14  15  16]]]


In [ ]:
tensor.size

12

In [ ]:
tensor.shape

(2, 2)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=59c466a3-ad43-41a1-9517-cab1096e0dcf' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>