In [ ]:
import numpy as np

Scalar, vector, matrix and tensor.

In [ ]:
scalar = 5.679
vector = np.array([3,4,5,6])
matrix = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3,30], [4,5,6,31], [7,8,9,32]],
    [[11,12,13,33], [14,15,16,34], [17,18,19,35]],
    [[21,22,23,36], [24,25,26,37], [27,28,29,38]]
])

# Transpose

## Scalar

In [ ]:
escalar_t = scalar.T 

AttributeError: 'float' object has no attribute 'T'

## Vector

In [ ]:
vector_t = vector.T
print(vector)
print(vector_t)


[3 4 5 6]
[3 4 5 6]


## Matrix

In [ ]:
matrix_t = matrix.T
print(matrix)
print(matrix_t)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [ ]:
matrix.shape

(3, 2)

In [ ]:
matrix_t.shape

(2, 3)

## Tensor

In [ ]:
tensor_t = tensor.T
tensor_t


array([[[ 1, 11, 21],
        [ 4, 14, 24],
        [ 7, 17, 27]],

       [[ 2, 12, 22],
        [ 5, 15, 25],
        [ 8, 18, 28]],

       [[ 3, 13, 23],
        [ 6, 16, 26],
        [ 9, 19, 29]],

       [[30, 33, 36],
        [31, 34, 37],
        [32, 35, 38]]])

In [ ]:
tensor

array([[[ 1,  2,  3, 30],
        [ 4,  5,  6, 31],
        [ 7,  8,  9, 32]],

       [[11, 12, 13, 33],
        [14, 15, 16, 34],
        [17, 18, 19, 35]],

       [[21, 22, 23, 36],
        [24, 25, 26, 37],
        [27, 28, 29, 38]]])

In [ ]:
tensor.shape

(3, 3, 4)

In [ ]:
tensor_t.shape

(4, 3, 3)

In [ ]:
tensor_t_t = tensor_t.T
tensor_t_t

array([[[ 1,  2,  3, 30],
        [ 4,  5,  6, 31],
        [ 7,  8,  9, 32]],

       [[11, 12, 13, 33],
        [14, 15, 16, 34],
        [17, 18, 19, 35]],

       [[21, 22, 23, 36],
        [24, 25, 26, 37],
        [27, 28, 29, 38]]])

# Sum of matrices

In [ ]:
A = matrix
B = matrix_t
C = A+B

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [ ]:
A = np.array(([1,2],[3,4],[5,6]))
B = np.array(([3,4],[5,6],[1,2]))
C = A + B


In [ ]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
B

array([[3, 4],
       [5, 6],
       [1, 2]])

In [ ]:
C

array([[ 4,  6],
       [ 8, 10],
       [ 6,  8]])

In [ ]:
D = C + scalar
D

array([[ 9.679, 11.679],
       [13.679, 15.679],
       [11.679, 13.679]])

In [ ]:
P = np.random.randint(0,25,25).reshape(5,5)
P

array([[18, 23, 20, 12,  6],
       [ 1, 17,  6, 24, 18],
       [16, 19, 10, 19, 21],
       [11,  6,  0,  9, 20],
       [ 8, 17,  3, 22, 19]])

In [ ]:
P_t = P.T
P_t

array([[18,  1, 16, 11,  8],
       [23, 17, 19,  6, 17],
       [20,  6, 10,  0,  3],
       [12, 24, 19,  9, 22],
       [ 6, 18, 21, 20, 19]])

In [ ]:
sum_of_P = P + P_t
sum_of_P

array([[36, 24, 36, 23, 14],
       [24, 34, 25, 30, 35],
       [36, 25, 20, 19, 24],
       [23, 30, 19, 18, 42],
       [14, 35, 24, 42, 38]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=59c466a3-ad43-41a1-9517-cab1096e0dcf' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>