In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([3,4,5])
matriz = np.array(([1,2],[3,4],[5,6]))

In [3]:
A = vector + matriz

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [5]:
matriz.T

array([[1, 3, 5],
       [2, 4, 6]])

In [4]:
A = vector + matriz.T
A

array([[ 4,  7, 10],
       [ 5,  8, 11]])

# Broadcasting

In [6]:
colum_vector = np.array([1,2,3,4,5]).reshape(5,1)
row_vector = np.array([1,2,3,4,5])
matrix_5x5 = np.arange(0,25).reshape(5,5)
matrix_5x5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## Broadcasting column vector

In [7]:
broadcasting_colum = matrix_5x5 + colum_vector
broadcasting_colum

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

## Broadcasting row vector

In [8]:
broadcasting_row = matrix_5x5 + row_vector
broadcasting_row

array([[ 1,  3,  5,  7,  9],
       [ 6,  8, 10, 12, 14],
       [11, 13, 15, 17, 19],
       [16, 18, 20, 22, 24],
       [21, 23, 25, 27, 29]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=59c466a3-ad43-41a1-9517-cab1096e0dcf' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>